export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const REQ_LOG_USER_INFO = "REQ_LOG_USER_INFO";
export const LOG_USER_INFO_SUCCESS = "LOG_USER_INFO_SUCCESS";
export const LOG_USER_INFO_FAILURE = "LOG_USER_INFO_FAILURE";

export const ADD_SUBJ_REQUEST = "ADD_SUBJ_REQUEST";
export const ADD_SUBJ_SUCESS = "ADD_SUBJ_SUCESS";
export const ADD_SUBJ_FAILED = "ADD_SUBJ_FAILED";

export const FETCH_SUBJ_REQUEST = "FETCH_SUBJ_REQUEST";
export const FETCH_SUBJ_SUCESS = "FETCH_SUBJ_SUCESS";
export const FETCH_SUBJ_FAILED = "FETCH_SUBJ_FAILED";

export const FETCH_CLASS_REQUEST = "FETCH_CLASS_REQUEST";
export const FETCH_CLASS_SUCESS = "FETCH_CLASS_SUCESS";
export const FETCH_CLASS_FAILED = "FETCH_CLASS_FAILED";

export const FETCH_TOPICS_REQUEST = "FETCH_TOPICS_REQUEST";
export const FETCH_TOPICS_SUCESS = "FETCH_TOPICS_SUCESS";
export const FETCH_TOPICS_FAILED = "FETCH_TOPICS_FAILED";

export const UPLOAD_VIDEO_REQUEST = "UPLOAD_VIDEO_REQUEST";
export const UPLOAD_VIDEO_SUCCESS = "UPLOAD_VIDEO_SUCCESS";

export const UPLOAD_DOC_REQUEST = "UPLOAD_DOC_REQUEST";
export const UPLOAD_DOC_SUCCESS = "UPLOAD_DOC_SUCCESS";

export const FETCH_ENROLLED_COURSES_REQUEST = "FETCH_ENROLLED_COURSES_REQUEST";
export const FETCH_ENROLLED_COURSES_SUCESS = "FETCH_ENROLLED_COURSES_SUCESS";
export const FETCH_ENROLLED_COURSES_FAILED = "FETCH_ENROLLED_COURSES_FAILED";

export const ADD_QUESTION_REQUEST = "ADD_QUESTION_REQUEST";
export const ADD_QUESTION_SUCESS = "ADD_QUESTION_SUCESS";
export const ADD_QUESTION_FAILED = "ADD_QUESTION_FAILED";

export const FETCH_QUESTION_REQUEST = "FETCH_QUESTION_REQUEST";
export const FETCH_QUESTION_SUCESS = "FETCH_QUESTION_SUCESS";
export const FETCH_QUESTION_FAILED = "FETCH_QUESTION_FAILED";

export const RECORD_CLASSID = "RECORD_CLASSID";
export const RECORD_QSTID = "RECORD_QSTID";
export const RECORD_ANSID = "RECORD_ANSID";

export const FETCH_ANSWERS_REQUEST = "FETCH_ANSWERS_REQUEST";
export const FETCH_ANSWERS_SUCCESS = "FETCH_ANSWERS_SUCCESS";
export const FETCH_ANSWERS_FAILED = "FETCH_ANSWERS_FAILED";